### ISSUE TITLE
Tcp connection is not closed

### ISSUE THREAD

**Issue by yejiayu** [actix/actix-net#100]
I'm doing performance testing for an HTTP server built on actix-web.

On my server, set `ulimit -n 1024` while simultaneously opening 1200 connections on another server for performance testing.

When `too many open files` error occurs in the HTTP server, I kill the HTTP performance test program, and then checked the server's TCP connection status (`netstat -na | grep server_port`) and found that many TCP connections were in the `CLOSE_WAIT` state and waited for several hours without release connections.

I found the code where `too many open files` happened.
https://github.com/actix/actix-net/blob/4f2910c6b301032d09bc2cedd0f259bb008788e1/actix-server/src/accept.rs#L420

Based on this code I have 2 questions

1. Will the entire HTTP server stop working after `accept` returns?
2. Could it cause the connection not to drop?

**Comment by Malanche** [comment]
In my case, a server starts gathering CLOSE_WAIT connections until it cannot open more tcp connections. I have two different versions of the code, and only one presents the issue, so I will walk my way from one code to the other to try to find the issue.

**Comment by fakeshadow** [comment]
I believe this is already fixed by master branch. Please reply for discussion if it still presist and examples to reproduce would be welocmed. There is no way to progress without code to show the problem.
