### ISSUE TITLE
Extreme indirection with actix-server

### ISSUE THREAD

**Issue by Diggsey** [actix/actix-net#123]
When you want to run a TCP server, you first bind a "service factory":

```rust
pub fn bind<F, U, N: AsRef<str>>(self, name: N, addr: U, factory: F) -> Result<Self>
where
    F: ServiceFactory<TcpStream>,
    U: ToSocketAddrs,
```

(Despite what the type parameters initial, this is not going to be...)

So you go and look at the `ServiceFactory` trait...

```rust
pub trait ServiceFactory<Stream: FromStream>: Send + Clone + 'static {
    type Factory: actix::ServiceFactory<Config = (), Request = Stream>;

    fn create(&self) -> Self::Factory;
}
```

And find that it's not just a factory, it's a ServiceFactoryFactory! What is this, Java?

That's a minor annoyance, so let's see what it takes to implement `actix::ServiceFactory`:

```rust
pub trait ServiceFactory {
    type Request;
    type Response;
    type Error;
    type Config;
    type Service: Service<Request = Self::Request, Response = Self::Response, Error = Self::Error>;
    type InitError;
    type Future: Future<Output = Result<Self::Service, Self::InitError>>;
    fn new_service(&self, cfg: Self::Config) -> Self::Future;

    ...
}
```

Cool, so this is a factory that asynchronously produces something that implements `Service`. That's a little complicated but fair. Except... I don't remember seeing all these associated types being locked down.

Looking back, we see that `Config` is specified to be empty, and `Request` is specified to be a `Stream`. That's weird... We're only going to get one stream per connection, so why did we even need to model this as a "service". Furthermore, `Response` is left unspecified so presumably does not even get used.

What's going on here? Is a new service created for each connection? If that's the case why have the service trait at all? Is the same service reused for multiple connections? Then why have two levels of "service factories" and why does one of them need to be async?

**Comment by fafhrd91** [comment]
actix requires extra factory because it is single threaded. actix_server::ServiceFactory produces app ServiceFactory in each worker thread and it is `Send + Clone`, basically it is definition 
for `Fn() -> impl ServiceFactory<Io>`. for example, all actix-web examples contains following code

```rust

HttpServer::new(|| {
        App::new()
          ...
})
```

closure that creates `App` is actix_server::ServiceFactory

**Comment by cdbattags** [comment]
@fafhrd91 and/or @Diggsey:

Any recommendations to cleanup the types/struct now that we're open to breaking changes moving towards a 3.0 milestone?

@fafhrd91 and anything you think that's maybe leftover here from the async/await refactors that we might be able to tackle?

**Comment by fafhrd91** [comment]
refactoring is a task for new maintainers.

**Comment by cdbattags** [comment]
@fafhrd91 understood! Just curious if you personally had any suggestions in regards to this conversation?

**Comment by fafhrd91** [comment]
This is best design I could come up. Open PR is simple task, anyone could improve this code by opening pr
