### ISSUE TITLE
Complier the code twice(linux system),the executable file has difference

### ISSUE THREAD

**Issue by JhonGw** [actix/actix-net#151]
I complier the code twice(linux system),and compare the first executable file and second file by the "Beyond Compare",there has a difference.When i remove the line **let service: BoxedServerService = Box::new(StreamService::new(inner));**,the two executable file has no difference.

https://github.com/actix/actix-net/blob/7140c04c44842d15dda9caab3b8461f0c15adaa3/actix-server/src/service.rs#L153

The main.rs
```
use actix_web::{web, App, Responder, HttpServer};

async fn index() -> impl Responder {
    "Hello world!"
}

#[actix_rt::main]
async fn main() -> std::io::Result<()> {
    HttpServer::new(|| {
        App::new().service(
            web::scope("/app").route("/index.html", web::get().to(index)),
        )
    })
        .bind("127.0.0.1:8088")?
        .run()
        .await
}
```

Cargo.toml

```
[package]
name = "test1"
version = "0.1.0"
authors = [""]
edition = "2018"

[dependencies]
actix-web = {version = "=2.0.0", features=["rust-tls"] }
actix-rt = "=1.0.0"
```

**Comment by robjtede** [comment]
I don't really know what can be done from us.
