### ISSUE TITLE
manually setting workers(0) will actually spin 0 thread

### ISSUE THREAD

**Issue by adrian-wechner** [actix/actix-net#166]
Just a little thing, I noticed. at server building when you set .workers(0) then it will actually spin 0 threads and no request goes though. My expectation was that by setting 0, it would load whatever the default value for workers would be. Is it a bug or desired behavior? If bug, I'd be glad to send a PR.
right now with: actix-web "3.0.0-beta.1"

**Comment by robjtede** [comment]
I can't think of a use case for calling it with zero workers. Might be worth a warn log but I think the docs are pretty clear about it's behavior.

**Comment by adrian-wechner** [comment]
I absolutely agree with you that there doesn't seem a use case for 0 threads. 

Out of the docs:
`HttpServer automatically starts a number of http workers, by default this number is equal to the number of logical CPUs in the system. This number can be overridden with the HttpServer::workers() method.`

Essentially when you don't use the workers method, then you get the logic cpu count. When you set it to x you get x. What I am trying to get to, is there is a use case for workers(0). Essentially indicating that 'default' shall be used as 0 would not make any sense otherwise. therefore might rather be a feature request.

 I use it personally in our configuration system, that by setting 0 for the workers config, that we translate it into the system's cpu count. I think that this having upstream would make more sense, as I see no sense on allowing to have 0 threads anyway.

**Comment by robjtede** [comment]
> I use it personally in our configuration system, that by setting 0 for the workers config...

I think that's quite a compelling use-case for passing 0 in. PR would be welcome for this.
