### ISSUE TITLE
error[E0658]: use of unstable library feature 'matches_macro'

### ISSUE THREAD

**Issue by jaredforth** [actix/actix-net#193]
I am getting the following error when trying to compile a crate that depends on actix-utils: 

```rust
error[E0658]: use of unstable library feature 'matches_macro'
  --> /home/jared/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-utils-2.0.0/src/timeout.rs:61:38
   |
61 |             TimeoutError::Timeout => matches!(other, TimeoutError::Timeout),
   |                                      ^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/65721

error: aborting due to previous error
```

The [error in question](https://github.com/rust-lang/rust/issues/65721) was closed in October of 2019, but the compiler is complaining about line 61 in [timeout.rs](https://github.com/actix/actix-net/blob/master/actix-utils/src/timeout.rs). 

I am on Ubuntu on WSL(Windows Subsystem for Linux), and have the following versions of Rust tooling: 

- rustup 1.21.1
- rustc 1.41.1
- cargo 1.41.0

My rustup toolchain is: `stable-x86_64-unknown-linux-gnu (default)`. 

I have the following Actix related dependencies in the project: 

```rust
actix = { version="0.9.0", features=["http"] }
actix-multipart = "0.2.0"
actix-web = "2.0.0"
actix-rt = "1.0.0"
async-std = "1.4.0"
actix-cors = "0.2.0"
actix-web-httpauth = "0.4.1"
```

What could be causing this issue? I have successfully compiled this project within the last month and have never seen this problem before.

**Comment by robjtede** [comment]
Running `cargo tree -i actix-utils:2.0.0` will show the dependency path. All actix crates have a minimum supported version of rust 1.42 now, which is [when the matches macro was stabilized](https://caniuse.rs/features/matches_macro).

**Comment by jaredforth** [comment]
@robjtede Thanks! 

I updated to v1.46 and it's working now.
