### ISSUE TITLE
consider updating mio to v0.7

### ISSUE THREAD

**Issue by Silentdoer** [actix/actix-net#197]
like title.

**Comment by robjtede** [comment]
Let it be known I've started looking at this already.

**Comment by robjtede** [comment]
now that tokio 0.3 is out we can actually do this, though we will need to use a viable alternative to the message passing system since the one we currently use was removed from mio 0.7

**Comment by fakeshadow** [comment]
I have a partially working branch [here](https://github.com/fakeshadow/actix-net/tree/mio-0.7.3)

I have several issues block it to be fully working. mainly are:
1.`tokio-util` has updated to use the new `poll_read` and `ReadBuf` of tokio 0.3. I'm not sure if we should follow the path and replace all the bytesmut we are using. So I leave it out for now rendering `actix-code` not working.

2. certain rustls dep we use is not maintained and we may have to replace it/them with tokio 0.3 compat ones. 
so `actix-connect`'s rustls feature is unsable. (Could affect `actix-tls` too but I'm not sure if it's the case).

3. `mio` removed some API we used namely the `listener::accept_std` and I can't find a easy way to convert a mio stream to tokio one. So `actix-server` on my branch only works for unix system.

4. also `mio` would return different type of `SocketAddr` for uds between `accept` and `local_addr` and I have no idea how to convert between the two types so I left it out for now.(It's only used for logging from what I see but I could be wrong).

**Comment by JohnTitor** [comment]
@fakeshadow Awesome!

> 2. certain rustls dep we use is not maintained and we may have to replace it/them with tokio 0.3 compat ones.
>        so `actix-connect`'s rustls feature is unsable. (Could affect `actix-tls` too but I'm not sure if it's the case).

I'm not sure about this, it seems `tokio-rustls` is updated to use `tokio` v0.3 and other deps should be fine. Do you mean `trust-dns-*` crates?

**Comment by fakeshadow** [comment]
Sorry my bad. I'm not familiar with these crates and I must got confused on them. I just checked `tokio-rustls` it indeed is tokio 0.3 compat with 0.20.0. Thanks for the clarify.
