### ISSUE TITLE
Contention in arbiter code

### ISSUE THREAD

**Issue by bobrik** [actix/actix-net#205]
Disclaimer: I understand very little about how this works.

I'm using actix_web for my app and it works fabulously most of the time, thank you for working on it. My app is doing ~150krps from thousands of concurrent clients while burning half of a single 32 core Zen2 VM in GCP.

The issue I'm having is that sometimes my app would enter a state where all CPUs are burning mostly in scheduling code, while barely accepting any client connections and making health checks unhappy. Number of open file descriptors quickly blows well over a million and memory balloons over 32GB (mostly not RSS, but also not SLAB, so I'm quite bamboozled there too), when normally it's well under under 8GB.

Here's how an on-CPU flamegraph looks like (there's Kafka on the right, it's safe to ignore it):

![image](https://user-images.githubusercontent.com/89186/97062670-d597e280-1550-11eb-9d4a-68e0202b246d.png)

At the top we're looking at mostly `try_read_output` doing most of the work:

![image](https://user-images.githubusercontent.com/89186/97062691-eba5a300-1550-11eb-86c7-f77da5e42fc9.png)

Zoomed into the left pillar:

![image](https://user-images.githubusercontent.com/89186/97062704-f52f0b00-1550-11eb-83eb-61830677014a.png)

Zoomed into the right pillar:

![image](https://user-images.githubusercontent.com/89186/97062707-fceeaf80-1550-11eb-879d-be6a8bbd06fe.png)

One thing that helps here is not allowing clients to reuse connections, which keeps number of open files in check, but also cripples throughput. I have two services in a single app (client facing an metrics), and metrics is accessible just fine when client facing is suffering. Same happens when I replace client facing code with a service that just replies with 200 OK without doing anything.

Compare this to a flamegraph in a steady state (purple is `try_read_output`):

![image](https://user-images.githubusercontent.com/89186/97063115-c74ac600-1552-11eb-9f2f-9832d649db41.png)

It's not exactly great with respect to spinlock contention in kernel networking code on the right (I suspect it's actix related, but it's not something I had time to confirm or worry about), but the problematic pillars are much narrower and they are not as exclusive to `try_read_output`, there are some other cpu consumers in them as well.

**Comment by fafhrd91** [comment]
it seems, your or some other code panics and actix restarts thread. try panic=abort in your cargo.toml

**Comment by bobrik** [comment]
I'll definitely try `panic=abort` if it happens again, but shouldn't all panics end up as log messages in `stderr`? I've seen my code panic due to `HttpRequest::peer_addr()` returning `None` when file descriptors are exhausted, but that was explicit with an error message, and the consequence was CPU usage dropping to near zero, not skyrocketing.

**Comment by bobrik** [comment]
Nope, `panic = "abort"` did not help.

**Comment by bobrik** [comment]
Correction: I used the wrong binary, so it's still unknown whether `panic = "abort"` helps.

**Comment by bobrik** [comment]
Checked again and `panic = "abort"` doesn't trigger any aborts, so it's something else.

It's really interesting that out of two apps in the same process, the unloaded one with metrics responds to a health check just fine, while the loaded user-facing one doesn't send any response.

**Comment by bobrik** [comment]
If it's of any help, my app mostly reads data from clients (for 2.0Gbps coming in we only send 0.3Gbps out).

**Comment by fafhrd91** [comment]
i checked graphs again, you right this is not panic. this is new code, so question to new maintainers

**Comment by bobrik** [comment]
Another interesting observation: after getting the service into a stable state, I can see that after a restart some workers are saturated (note the top bunch at 100%):

![image](https://user-images.githubusercontent.com/89186/97213539-f776ac80-177e-11eb-8430-a8cfe207e070.png)

If I pin one of those to a single CPU and take a flamegraph of that CPU, I get the following flamegraph:

![image](https://user-images.githubusercontent.com/89186/97213626-1bd28900-177f-11eb-8362-727f1e09391c.png)

If I take a flamegraph of a more reasonably loaded CPU, I get this:

![image](https://user-images.githubusercontent.com/89186/97213671-2a20a500-177f-11eb-967d-bcb4c5d1d3c3.png)

I've highlighted `actix_rt::arbiter::CleanupPending` on both flamegraphs.

Eventually all workers return to a normal state when nothing is at 100%, but the state of a single overloaded worker looks suspiciously similar to the system-wide state when everything is overloaded:

![image](https://user-images.githubusercontent.com/89186/97213867-75d34e80-177f-11eb-9958-d7859d770a3f.png)

cc @Jonathas-Conceicao, since https://github.com/actix/actix-net/pull/128 introduced `CleanupPending`

**Comment by fakeshadow** [comment]
https://github.com/actix/actix-net/issues/206.
I think point 2 of the issue is related. We should not collect join handles.
