### ISSUE TITLE
Consider remove RUNNING, Q and PENDING thread locals from actix-rt

### ISSUE THREAD

**Issue by fakeshadow** [actix/actix-net#206]
For now every `actix_rt::spawn` would go through these thread locals. 
This brings up several questions:

1. We check `RUNNING` and if it's false we box the future and push it to `Q`. This seems only useful when we want to spawn futures before tokio runtime setup but interanlly we can totally aviod that. Is it useful in user code? 

2. Whenever a future is spawned we push it's `JoinHandle` to `PENDING` and if `PENDING` goes large enough we would actively poll these handles and remove the resolved ones. This seems useful but what if user have a stream oriented endpoint that would spawn a long live future with every incoming request. Wouldn't that make `PENDING` grows very big and we would poll them all once with every new spawn?

3. `PENDING` is also used for `Arbiter::local_join` for clearing all pending futures by wait for them to resolve. This features is kind useful but I can't find anywhere we use it. I serached actix and actix-web repo and it's no where to be found.

**Comment by robjtede** [comment]
@Jonathas-Conceicao might have something to contribute here.

**Comment by fakeshadow** [comment]
Interestingly the `try_read_output` mentioned in other issue is what would run when polling a join handle.

**Comment by bobrik** [comment]
I am happy to try out any proposed changes in the next couple of days (going into the woods later).

Seems like I should be able to see at least reduced `try_read_output` during normal operation.

**Comment by bobrik** [comment]
I've tried the following (regarding the second point):

```diff
diff --git a/actix-rt/src/arbiter.rs b/actix-rt/src/arbiter.rs
index eff10ca..6705490 100644
--- a/actix-rt/src/arbiter.rs
+++ b/actix-rt/src/arbiter.rs
@@ -18,14 +18,12 @@ use crate::system::System;
 
 use copyless::BoxHelper;
 
-use smallvec::SmallVec;
 pub use tokio::task::JoinHandle;
 
 thread_local!(
     static ADDR: RefCell<Option<Arbiter>> = RefCell::new(None);
     static RUNNING: Cell<bool> = Cell::new(false);
     static Q: RefCell<Vec<Pin<Box<dyn Future<Output = ()>>>>> = RefCell::new(Vec::new());
-    static PENDING: RefCell<SmallVec<[JoinHandle<()>; 8]>> = RefCell::new(SmallVec::new());
     static STORAGE: RefCell<HashMap<TypeId, Box<dyn Any>>> = RefCell::new(HashMap::new());
 );
 
@@ -181,16 +179,7 @@ impl Arbiter {
     {
         RUNNING.with(move |cell| {
             if cell.get() {
-                // Spawn the future on running executor
-                let len = PENDING.with(move |cell| {
-                    let mut p = cell.borrow_mut();
-                    p.push(tokio::task::spawn_local(future));
-                    p.len()
-                });
-                if len > 7 {
-                    // Before reaching the inline size
-                    tokio::task::spawn_local(CleanupPending);
-                }
+                tokio::task::spawn_local(future);
             } else {
                 // Box the future and push it to the queue, this results in double boxing
                 // because the executor boxes the future again, but works for now
@@ -317,34 +306,9 @@ impl Arbiter {
     /// Returns a future that will be completed once all currently spawned futures
     /// have completed.
     pub fn local_join() -> impl Future<Output = ()> {
-        PENDING.with(move |cell| {
-            let current = cell.replace(SmallVec::new());
-            future::join_all(current).map(|_| ())
-        })
-    }
-}
-
-/// Future used for cleaning-up already finished `JoinHandle`s
-/// from the `PENDING` list so the vector doesn't grow indefinitely
-struct CleanupPending;
-
-impl Future for CleanupPending {
-    type Output = ();
-
-    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
-        PENDING.with(move |cell| {
-            let mut pending = cell.borrow_mut();
-            let mut i = 0;
-            while i != pending.len() {
-                if let Poll::Ready(_) = Pin::new(&mut pending[i]).poll(cx) {
-                    pending.remove(i);
-                } else {
-                    i += 1;
-                }
-            }
-        });
-
-        Poll::Ready(())
+        async {
+            todo!("No, This Isn't How You're Supposed To Play The Game");
+        }
     }
 }
 
@@ -381,15 +345,7 @@ impl Future for ArbiterController {
                         return Poll::Ready(());
                     }
                     ArbiterCommand::Execute(fut) => {
-                        let len = PENDING.with(move |cell| {
-                            let mut p = cell.borrow_mut();
-                            p.push(tokio::task::spawn_local(fut));
-                            p.len()
-                        });
-                        if len > 7 {
-                            // Before reaching the inline size
-                            tokio::task::spawn_local(CleanupPending);
-                        }
+                        tokio::task::spawn_local(fut);
                     }
                     ArbiterCommand::ExecuteFn(f) => {
                         f.call_box();

```

There's a high chance it prevents catastrophic overload from #205, since it eliminates the whole `CleanupPending`.

It also increase my app's per core throughput in a happy state ~3%, which is nice.

**Comment by fakeshadow** [comment]
Yea that's basically it. Getting rid of running would require some changes to the construct methods and I doubt an extra branch would make much difference so the rest can be dealt with later. Idealy actix_rt::spawn should really just be an alias for spawn_local

**Comment by fakeshadow** [comment]
After some digging it looks like remove Running and Q would be a breaking change for actix. Also to actix-web but purely internal.

Without them someting like this would not work anymore.
```rust
fn main() {
    let sys = System::new("example");
    let addr = MyActor.start(); // We can't get into the system's tokio context.
    sys.run();
}
```

Instead this would have be changed to something like this.
```rust
fn main() {
    let mut sys = System::new("example");
    let addr = sys.block_on(async{ MyActor.start() // we are in tokio context }); 
    sys.run();
}
```

to be honest this is some legacy stuff with old futures.Nowadays most people use actix with wrapping everying in the `block_on` so most people would not notice if we apply this change. 

I think this is a worth trade off.We have a slightly complicated actor init.(If we don't init the system with marco or a block_on for whatever reason). We get rid of a branch everytime we spawn a future.(which happens a lot at runtime)
