### ISSUE TITLE
[service]: `ServiceFactory` and `Transform` maybe need cleanup

### ISSUE THREAD

**Issue by arniu** [actix/actix-net#209]
When I tried to write a simple middleware, I found I have to add **10** associated types!
**6** for `Transform` and `4` for `Service`.
It's really horrible!

I don't know why they designed like this.

## `Transform` 

A `Transform`  create a new service with the given  one, so:

* The associated type `Transform` is confusing, rename to `Service`?
* The associated type `Request`, `Response` and `Error` are redundant.
* And for the return type, a `Future` is over-designed.

After searching `new_transform` among [actix-net], [actix-web] and [actix-extras], 
I found almost all the associated `Future` were `Ready`s.

In fact, there is no need to `async` compose services. 

If so, it will be much easier to write middlewares.

[actix-net]: https://github.com/actix/actix-net/search?q=new_transform
[actix-web]: https://github.com/actix/actix-web/search?q=new_transform
[actix-extras]: https://github.com/actix/actix-extras/search?q=new_transform

## `ServiceFactory`

The associated type `Request`, `Response` and `Error` are redundant.

> This is my first impression of actix-service.
> I hope I was wrong. Please don't fire on me.

**Comment by fakeshadow** [comment]
Think about it. Let's say you have a bunch of single thread tasks(!Send futures for example) at hand but you want to send it to another thread and run it. What would you do?

You can use this issue as reference. https://github.com/actix/actix-net/issues/123

There could be better design but the current one is not bad at all by any means.

**Comment by fakeshadow** [comment]
Short example:
```rust
async fn send_me() {
    let rc = std::rc::Rc::new(123);
    tokio::time::delay_for(std::time::Duration::from_millis(1)).await;
    let no_send = rc.clone();
}

fn main() {
    let task = send_me();

    std::thread::spawn(move || {
       // How?
       let task = task;
    }).join().unwrap();
}
```

**Comment by arniu** [comment]
I know what you mean.

Shall we remove the redundant associated types to make it simple? Take `ServiceFactory` for example: 

```patch
pub trait ServiceFactory {
-   /// Requests handled by the created services.
-   type Request;
-   /// Responses given by the created services.
-   type Response;
-   /// Errors produced by the created services.
-   type Error;

    /// Service factory configuration.
    type Config;

    /// The kind of `Service` created by this factory.
-   type Service: Service<
-      Request = Self::Request,
-       Response = Self::Response,
-       Error = Self::Error,
-   >;
+   type Service: Service;

    /// Errors potentially raised while building a service.
    type InitError;

    /// The future of the `Service` instance.
    type Future: Future<Output = Result<Self::Service, Self::InitError>>;

    /// others ...
}
```

**Comment by fakeshadow** [comment]
They are not redundant. There are complex ServiceFactory chain in actix-web where multiple ServiceFactories are wrapped where the output are altered with each layer. You just push the describe of the output types to generic types that you would find yourself add many.

It's better you try your idea on `actix-service` and make it work first.

**Comment by fakeshadow** [comment]
I personally have a lot of services instance themselves with async transform.

It's there so you can have async. It's Ok you don't use them but it's not an over design.

actix-web is generic over solely on these traits. Limit them would affect every end user's ability to write async code.

**Comment by arniu** [comment]
Thanks for your response.

What the `Transform` does is to compose `Service`s, just like `compose` in other frameworks. All the async logic can be move out of `Transform`, or pushed down to `Service`.

**Comment by fakeshadow** [comment]
Nope. If you move the factory functionality to Service you would be running the factory functions with every service call.
That's at least one additional branch you pay at runtime and would make your service call more complicated.

**Comment by robjtede** [comment]
I'm considering this issue closed. The associated types on Transform and ServiceFactory are there by design. Admitedly, Transform::Transform is a bit weird but with good docs we can live with it.
