### ISSUE TITLE
Update trust-dns-resolver vendor to use linked-hash-map 0.5.3

### ISSUE THREAD

**Issue by sudarshan-reddy** [actix/actix-net#220]
Rust 1.48 introduces a check that causes a panic if the inner types have mem::uninitialized and aren't initialised. The version of trust-dns-resolver used by actix-connect uses a version of linked-hash-map that would panic if written to on Rust version 1.48. 

The newest version of trust-dns-resolver uses the version of linked-hash-map with the fix(https://github.com/contain-rs/linked-hash-map/pull/100/files).

**Comment by JohnTitor** [comment]
I'm not sure if we have an actionable item here and would like just to close this issue as wontfix. The current dependency tree looks like:

```
└── trust-dns-resolver v0.19.6
    ├── lru-cache v0.1.2
    │   └── linked-hash-map v0.5.3
...
```

I presume you don't mean v5.3 but v0.5.3, `actix-connect v2.0.0` depend on `trust-dns-resolver ^0.19` and it should pull `linked-hash-map v0.5.3`. So I think there's no issue on the actix side.

Anyway, `dns-resolver` will be updated to `v0.20.0` (which is currently alpha stage) in #204 as it updates tokio runtime.

**Comment by sudarshan-reddy** [comment]
You are correct. I meant 0.5.3. May I ask how you are seeing this dependency tree please? When I build actix-net locally, linked-hash-map verson picked seems to be v0.5.0.

**Comment by JohnTitor** [comment]
You can see the tree by `cargo tree` command, newer cargo should have that subcommand.

> When I build actix-net locally, linked-hash-map verson picked seems to be v0.5.0.

Could you run `cargo update`? It may resolve your issue.

**Comment by sudarshan-reddy** [comment]
Just ran an update and this is indeed the case. Thanks @JohnTitor . I will mark this issue closed.
