### ISSUE TITLE
ConnectAddrsIter would always return Some on One variant

### ISSUE THREAD

**Issue by fakeshadow** [actix/actix-net#251]
https://github.com/actix/actix-net/blob/45edff625e194ff21223f67e41cd2fb5b5e007c8/actix-tls/src/connect/connect.rs#L178

`One<Option<Addr>>` was mainly used to have an easy take on the addr instead of copy. So this should be changed self to None variant after the copy.

**Comment by robjtede** [comment]
good catch, thanks.

fixed in a633d2353c5f9281a5a3ba274fef1f4f0147d4cf
