### ISSUE TITLE
Threads leak when server is stopped

### ISSUE THREAD

**Issue by sethm** [actix/actix-net#259]
# Description

I am currently working on a project that uses `actix-web` 3.3.2 and which creates and runs an actix `HttpServer` in a thread. The project allows the server to be stopped and dropped, and a new server created (e.g. for a configuration update) without exiting the main program.

We have discovered that the `actix-rt` worker threads are leaking when the server is stopped and dropped. After a server has been told to stop, with e.g.

    rt::System::new("").block_on(srv.stop(true));

any spawned `actix-net` workers with 0 active connections will fail to exit, even after the server is dropped.

All threads appear to be blocking in in `actix-rt/src/arbiter.rs` in the main run loop on line 137:

    // run loop
    let _ = match rt.block_on(stop_rx) {
        Ok(code) => code,
        Err(_) => 1,
    };

# Steps to Reproduce

The thread leak is reproducible using a slightly modified version of the `run-in-thread` example under `actix/examples`.  I have [created an example repository here](https://github.com/sethm/actix-thread-leak) that can more easily demo the problem.

To reproduce, simply run the example code, and after a few start/stop cycles, connect with a debugger such as `lldb` and list threads. Threads continue to build up with each pass through the loop in `main.rs`.

**Comment by fakeshadow** [comment]
Who start a system is tasked with calling System::current().stop() to stop the system you are scoped in.

**Comment by sethm** [comment]
Explicitly calling `rt::System::current().stop()` in the `run_app()` function does not seem to change the issue I'm seeing. 

(Is this the correct place to call `System::current().stop()`?)

I'm still seeing all the worker threads, e.g., with 12 workers:

```
(lldb) thread list
Process 295541 stopped
* thread #1: tid = 295541, 0x00007f07290ab3bf libc.so.6`clock_nanosleep + 223, name = 'actix-thread-le', stop reason = signal SIGSTOP
  thread #2: tid = 295543, 0x00007f072932836c libpthread.so.0`__libc_read at read.c:26:10, name = 'ctrl-c'
  thread #3: tid = 295545, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #4: tid = 295546, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #5: tid = 295547, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #6: tid = 295548, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #7: tid = 295549, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #8: tid = 295550, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #9: tid = 295551, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #10: tid = 295552, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #11: tid = 295553, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #12: tid = 295554, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #13: tid = 295555, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #14: tid = 295556, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #16: tid = 295596, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #17: tid = 295597, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #18: tid = 295598, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #19: tid = 295599, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #20: tid = 295600, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #21: tid = 295601, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #22: tid = 295602, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #23: tid = 295603, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #24: tid = 295604, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #25: tid = 295605, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #26: tid = 295606, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #27: tid = 295607, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #29: tid = 295668, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-thread-le'
  thread #30: tid = 295669, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #31: tid = 295670, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #32: tid = 295671, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #33: tid = 295672, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #34: tid = 295673, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #35: tid = 295674, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #36: tid = 295675, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #37: tid = 295676, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #38: tid = 295677, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #39: tid = 295678, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #40: tid = 295679, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #41: tid = 295680, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-rt:worker'
  thread #42: tid = 295681, 0x00007f07290ed5ce libc.so.6`epoll_wait + 94, name = 'actix-server ac'
```
I've pushed the small change I made to [my testbed](https://github.com/sethm/actix-thread-leak).

**Comment by robjtede** [comment]
There was a race condition thread leak from arbiters i found while working on rt recently. It might be fixed in master.

**Comment by sethm** [comment]
> There was a race condition thread leak from arbiters i found while working on rt recently. It might be fixed in master.

I'm not able to build against master right now due to some compilation errors in `actix-server-2.0.0-beta.2` that I haven't looked too closely at, but I did browse through the recent commits, and I think commit 2fa60b07ae7a3227de7d11097a0625f9ca19cb62 is probably going to fix this problem. Once I'm able to test, I'll update and let you know.

Is it likely that this will get backported to actix-web 3.x, or should we wait for actix-web 4.0?

**Comment by fakeshadow** [comment]
Could be fixed by https://github.com/actix/actix-net/pull/334

I noticed there are some branches missing Arbiter stop/

**Comment by fakeshadow** [comment]
I can not produce thread leak with a loop of server construction and immediate shutdown anymore so I think it's resolved.
Please ping me for re-open if the issue presist with latest master branch.
