### ISSUE TITLE
'actix-server accept loop' panic when resuming from sleep

### ISSUE THREAD

**Issue by Yoric** [actix/actix-net#263]
I don't know if this bug can affect web servers in production but I encounter it daily as a developer.

## Steps to reproduce

1. Build and launch an actix server (tested with Ubuntu 20.10).
2. Suspend the computer.
3. Resume the computer.

```log
thread 'actix-server accept loop' panicked at 'Poll error: Interrupted system call (os error 4)', /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:164:37
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: std::panicking::begin_panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:437
   2: actix_server::accept::Accept::poll_with::{{closure}}
             at /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:164
   3: core::result::Result<T,E>::unwrap_or_else
             at /home/yoric/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/result.rs:825
   4: actix_server::accept::Accept::poll_with
             at /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:162
   5: actix_server::accept::Accept::start::{{closure}}
             at /home/yoric/.cargo/registry/src/github.com-1ecc6299db9ec823/actix-server-2.0.0-beta.2/src/accept.rs:114
```

While the situation in which a server goes to sleep is unusual, I can think of applications that embed a web server for use on a desktop/laptop, which makes it a potential issue for some apps.

## Expected Behavior

The web server should be able to somehow resume activity when the computer wakes up.

## Your Environment

* Rust Version (I.e, output of `rustc -V`):1.48
* Actix Web Version: 2.0.0-beta.2

**Comment by shuoli84** [comment]
Also I've searched EINTR and tokio, then find the issue that tokio/async team decides swallow the EINTR for AsyncRead and AsyncWrite, though didn't mention what should happen on accept. The general idea is "retry error is not that useful for async code" I think?
Ref: https://github.com/rust-lang/futures-rs/issues/803#issuecomment-368617707

**Comment by shuoli84** [comment]
> ```rust
>             if let Err(e) = self.poll.poll(&mut events, None) {
>                 if e.kind() == std::io::ErrorKind::Interrupted {
>                     continue;
>                 } else {
>                     panic!("Poll error: {}", e);
>                 }
>             }
> ```
> 
> I personally think interrupted should not be handled. mio remove the auto retry for a reason. so I would leave the change to others.

Seems the reason to remove this in mio is to reduce api surfaces, and in tokio-rs, they retried this Err.  I think this is a proper fix to introduce into actix-net, otherwise, end user will see more panics or hanging.
ref: https://github.com/tokio-rs/mio/issues/494

**Comment by fakeshadow** [comment]
@shuoli84 There is a recent change to related code in #353 and would possibly work into next release. Please ping me if it has side effect on the behavior of sleep.
