### ISSUE TITLE
'System is not running' for actix_rt 2.0.2

### ISSUE THREAD

**Issue by Kasega0** [actix/actix-net#281]
I updated the actix_rt version from `1.1.1` to `2.0.2` and have since been getting the following error:

```
thread 'main' panicked at 'System is not running', ....../actix-rt-1.1.1/src/system.rs:78:21
```

Following program can reproduce this error:

```
use actix_web::{get, App, HttpResponse, HttpServer};

#[get("/")]
async fn index() -> Result<HttpResponse, actix_web::Error> {
    let response_body = "Hello world!";
    Ok(HttpResponse::Ok().body(response_body))
}

#[actix_rt::main]
async fn main() -> Result<(), actix_web::Error> {
    HttpServer::new(move || App::new().service(index))
        .bind("0.0.0.0:8080")?
        .run()
        .await?;
    Ok(())
}
```

cargo.toml

```
[package]
name = "sample"
version = "0.1.0"
authors = ["kasega0"]
edition = "2018"

[dependencies]
actix-web = "3.3.2"
actix-rt = "1.1.1"
# actix-rt = "2.0.2"
```

I also saw the same error when the version of `actix-web` was `2.0.0`.

Is there a combination of version numbers or something obvious I'm missing to get these to work together?

**Comment by robjtede** [comment]
actix web v3 does not support rt v2 (except in current beta)

**Comment by robjtede** [comment]
it is advisable to not use rt as a direct dependency if you can, the correct rt crate is re-exported @ `actix_web::rt`

**Comment by alecmocatta** [comment]
It's probably worth in future synchronizing publishing of non-beta releases to crates.io to avoid this? i.e. ensuring that the most-recent non-beta releases are compatible. I had to help after a colleague got stuck on this error, plus I just saw [this comment](https://stackoverflow.com/questions/66300243/system-is-not-running-for-actix-rt-2-0-2/66334156?noredirect=1#comment117530043_66334156) on stackoverflow which, to be honest, I can empathise with.

**Comment by joepio** [comment]
Not sure why I used `actix_rt` directly (probably from some old example .rs file?). 

Fixed this by changin `#[actix_rt::main]` to `#[actix_web::main]` and removing `actix_rt` from my `cargo.toml`.

**Comment by robjtede** [comment]
@lamafab simply because `actix_web::test` is already a thing; a testing helper module.

**Comment by lamafab** [comment]
@robjtede Thanks for the info. I already discovered it in v0.11.x of `actix` as described in https://github.com/actix/actix/issues/485#issuecomment-845502217

> Additionally, you can now expose the `#[actix::test]` macro directly by enabling it as a feature for `actix` (`features = ["macros"]`), so you no longer need to pull `actix-rt` for this.

**Comment by JoseM111** [comment]
> Not sure why I used `actix_rt` directly (probably from some old example .rs file?).
> 
> Fixed this by changin `#[actix_rt::main]` to `#[actix_web::main]` and removing `actix_rt` from my `cargo.toml`.

Worked for me. Thank you 🙏🏾
