### ISSUE TITLE
Large shutdown_timeout causes panic when calculating Instant

### ISSUE THREAD

**Issue by mlodato517** [actix/actix-net#298]
**The Issue**
Setting a [`shutdown_timeout`](https://docs.rs/actix-web/3.3.2/actix_web/struct.HttpServer.html#method.shutdown_timeout) of `u64::MAX` causes the following panic:
```
thread 'actix-rt:worker:1' panicked at 'overflow when adding duration to instant', library/std/src/time.rs:368:33
```
**Cause**
https://github.com/actix/actix-web/pull/849 increased the maximum shutdown timeout and [`Instant::add`](https://doc.rust-lang.org/src/std/time.rs.html#366-376) panics if the date can't be represented.

**Possible Solution**
Use [`checked_add`](https://doc.rust-lang.org/std/time/struct.Instant.html#method.checked_add) or document that `shutdown_timeout` can cause a panic if the value is too large.

**Note**
I also tried `u32::MAX` and I got a different panic:
```
thread 'actix-rt:worker:1' panicked at 'timer error: timer duration exceeds maximum duration', /home/mark/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/time/delay.rs:115:23
```
so I'm not sure if there needs to be further restrictions.

**Comment by mlodato517** [comment]
Oh I like your solution better :-)

**Comment by robjtede** [comment]
yeah turns out Tokio's thought about this with their `Instant::far_future` (but sadly private) method
