### ISSUE TITLE
Reduce dependencies and achieve more independence

### ISSUE THREAD

**Issue by zmlzm** [actix/actix-net#36]
Tokio 0.2 maybe a big broken and futures too. like :
https://github.com/tokio-rs/tokio/issues/1264
https://github.com/tokio-rs/tokio/issues/1318
https://github.com/tokio-rs/tokio/issues/887

I think it is hard or more time fot actix-* fellow this.  should we consider Reduce tokio dependencies and achieve more independence. 

at least we can port tokio-executor, tokio-current-thread  to actix. we already port the actix-codec. maybe other crates can fellow if need.

I think it good for maintain,  update and Contribution. is this good idea?

**Comment by fafhrd91** [comment]
I do t think this is good idea. actix-codec exists only because it provides different implementation of Framed object. I would prefer to reduce amount of code to support

**Comment by zmlzm** [comment]
This is NP,  fellow this https://github.com/actix/actix-web/issues/955
I want to know when actix-* update, Is there a roadmap?

**Comment by krircc** [comment]
@fafhrd91 There is also [async-std](https://async.rs/blog/announcing-async-std/) library.  [like this 1.0](https://async.rs/blog/announcing-async-std/#the-path-towards-1-0), maybe it is a good choose.

**Comment by fafhrd91** [comment]
async-std is not compatible with actix

**Comment by krircc** [comment]
you are right.
