### ISSUE TITLE
thread 'actix-rt|system:0|arbiter:6' panicked at 'called `Result::unwrap()` on an `Err` value: Incomplete', src/web.rs:14:42

### ISSUE THREAD

**Issue by k-bx** [actix/actix-net#404]
Not sure how bad this is, but looks somewhat scary, decided it's better to make a ticket.

```
thread 'actix-rt|system:0|arbiter:6' panicked at 'called `Result::unwrap()` on an `Err` value: Incomplete', src/web.rs:14:42
```

actix-rt is `2.2.0`, actix-web is `4.0.0-beta.9`

**Comment by robjtede** [comment]
Panics in user code are surfaced this way. It's likely not an actix problem. Run a backtrace to find the issue.
