### ISSUE TITLE
Default Actix (Tokio) runtime could not be created.

### ISSUE THREAD

**Issue by Algorab** [actix/actix-net#416]
I have a project where I use arm aticx musl mimalloc. When I run it on the raspberry I can see a error message in the title with running under valgrind.
I am not sure what cause the real problem. Due the message I think here is the right starting point.
A [arm-musl-mimalloc-actix repo](https://github.com/Algorab/arm-musl-mimalloc-actix) is available for reproduce the error and
everything is explained in more detail.

I start rust programming a view month ago, so my experience isn't very deep. Hope somebody can help me or point me to the right direction. And if only someone confirms that it is a bug.

**Comment by robjtede** [comment]
Try starting a Tokio runtime without the actix-rt wrapper. The error may expose more information.

Anyway there is nothing we can do about it so I'm going to close this. Any follow up should be filed against Tokio but likely is that they simply don't support that target (yet).
