### ISSUE TITLE
actix-server: Use SO_REUSEPORT instead of the acceptor thread

### ISSUE THREAD

**Issue by tontinton** [actix/actix-net#427]
Let the kernel load balance the connections between the worker threads using the SO_REUSEPORT feature.

This could make for an ever faster server, although it needs to be benchmarked.

I would like to know your opinions on this.

**Comment by fakeshadow** [comment]
actix-server support almost all platforms where tokio can run. In real the bare minimal of platform support would be Linux/MacOS/Windows.
If you can make reuse port work on all of them feel free to make PR for it.

BTW the acceptor's performance is not crucial. You would not notice any difference in traditional http benchmarks. The acceptor would only become a bottleneck when you never keep a tcp connection open and close it asap (Strictly no keep-alive and high concurrency at the same time) which is no sane person would do in real world.

**Comment by tontinton** [comment]
https://www.nginx.com/blog/socket-sharding-nginx-release-1-9-1/

Nginx tried it out and it seems they doubled their performance, maybe I'll play with it before opening a PR.

**Comment by fakeshadow** [comment]
Did you even read my reply? This is a shorter version if you did not bother to:

You can't get it work for all target platforms actix-server support.
You can't gain performance for any real world http workload.
