### ISSUE TITLE
Feature Request: add new feature `rustls-native-certs`

### ISSUE THREAD

**Issue by jonassmedegaard** [actix/actix-net#462]
Please consider adding new feature `rustls-native-certs` which uses rustls but instead of `webpki-roots` it uses `rustls-native-certs`.

**Comment by jirutka** [comment]
I second this request. Embedding CA certificates in a binary is a very bad idea and entirely unacceptable for Linux distributions.

**Comment by jirutka** [comment]
@robjtede ping

**Comment by robjtede** [comment]
hey @jirutka @jonassmedegaard let me know what you think about the changes in #506
