### ISSUE TITLE
publish actix-codec 0.5.1 to creates.io

### ISSUE THREAD

**Issue by toabctl** [actix/actix-net#483]
Hi,

can you please publish actix-codec version 0.5.1 to crates.io ? The version there is still 0.5.0

**Comment by JohnTitor** [comment]
Thanks for reporting!
Just published it at https://github.com/actix/actix-net/releases/tag/codec-v0.5.1
```sh
commit 855e3f96fe250d1cbba6acd49bdd6a4519c810b8 (HEAD, tag: tls-v3.0.4, tag: codec-v0.5.1)
Author: Rob Ede <robjtede@icloud.com>
Date:   Tue Mar 15 19:43:47 2022 +0000

    prepare actix-tls release 3.0.4
```

It's now available on crates.io: https://crates.io/crates/actix-codec/0.5.1
