### ISSUE TITLE
actix-tls 3.0.4 was never released

### ISSUE THREAD

**Issue by AldaronLau** [actix/actix-net#486]
The tag appears to have been created in March, but if you look on crates.io, the most recent version is 3.0.3

 - [git tag](https://github.com/actix/actix-net/tree/tls-v3.0.4)
 - [crates.io releases](https://crates.io/crates/actix-tls/versions)

**Comment by robjtede** [comment]
given we'll need to cut a release for the rustls 0.21 support, this will get done

**Comment by Originalimoc** [comment]
March, but in 2022? What happened?

**Comment by robjtede** [comment]
Just got forgotten, and wasn't a very important change.

**Comment by Originalimoc** [comment]
Just want to update rustls so there is not a red X on my toml file (っ °Д °;)っ hopefully release it soon
