### ISSUE TITLE
Crates.io page is outdated.

### ISSUE THREAD

**Issue by aikooo7** [actix/actix-net#492]
[The crates.io](https://crates.io/crates/local-waker) page makes the project appear unmaintained/dead since it doesn't have a readme.

**Comment by aikooo7** [comment]
3 weeks passed and no one showed up, is possible that I can do it or only a maintaner can do it? @robjtede

**Comment by robjtede** [comment]
Published:
- https://crates.io/crates/local-waker/0.1.4
- https://crates.io/crates/local-channel/0.1.5
- https://crates.io/crates/bytestring/1.3.1
