### ISSUE TITLE
Instructions in examples/basic.rs don't work

### ISSUE THREAD

**Issue by jorendorff** [actix/actix-net#5]
I'm probably doing something dumb, but the file says:

```rust
//! simple composite service
//! build: cargo run --example basic --features "ssl"
```

And I get:

```console
~/play/actix/actix-net/examples$ cargo run --example basic --features "ssl"
error: no example target named `basic`
```

**Comment by fafhrd91** [comment]
fixed.

if you'd like to check real examples, check actix-mqtt, actix-http, actix-web (1.0 branch). all this projects are built on top of actix-net
