### ISSUE TITLE
actix-macros don't support build on alpine(aarch64)

### ISSUE THREAD

**Issue by jenningsloy318** [actix/actix-net#523]
I tried to install https://github.com/SamTV12345/PodFetch on an alpine(aarch64) machine, but got error 
````
error: cannot produce proc-macro for `actix-macros v0.2.4` as the target `aarch64-unknown-linux-musl` does not support these crate types
````

**Comment by robjtede** [comment]
Some info on building for musl systems that sounds relevant:
- https://github.com/rust-lang/rust/issues/109699
- https://github.com/rust-lang/rust/issues/40174#issuecomment-538791091
