### ISSUE TITLE
New release of actix-server

### ISSUE THREAD

**Issue by Thomasdezeeuw** [actix/actix-net#586]
With Tokio v1.39 release Tokio is using Mio v1, would it be possible to release a new version of actix-server that include the update to Mio v1 (https://github.com/actix/actix-net/pull/577) as well?

**Comment by Thomasdezeeuw** [comment]
Thanks @robjtede. I might be missing something, but it still says that 2.4 is the latest release on crates.io for me (https://crates.io/crates/actix-server/versions). Did you publish to crates.io already?

**Comment by robjtede** [comment]
apologies my script didn't quite finish before getting off the train yesterday... published now
