### ISSUE TITLE
`actix-macros` isn't published to cargo.

### ISSUE THREAD

**Issue by stoksc** [actix/actix-net#68]
I want to pin to master to start trying stuff out but I get:
```
error: no matching package named `actix-macros` found
location searched: registry `https://github.com/rust-lang/crates.io-index`
required by package `actix-rt v1.0.0-alpha.1 (https://github.com/actix/actix-net#a0206459)`
    ... which is depended on by `actix-bb8-try v0.1.0 (/Users/b/rs/rust-service-template)
```
because `actix-macros` isn't published. I'm sure it's work in progress, but is there anyway to go ahead and publish it in an alpha version?

For now I can just patch it or use a fork of `actix-rt`, was just curious.

**Comment by fafhrd91** [comment]
You can override dependencies with patch section in cargo.toml

actix-web uses patch section

**Comment by stoksc** [comment]
I'll peek at that, didn't know I could do that. Sorry.
