### ISSUE TITLE
Chaining `bind` and `bind_rustls`/`bind_openssl` on the same port.

### ISSUE THREAD

**Issue by daxpedda** [actix/actix-net#75]
With @fafhrd91's help I figured out how to chain `HttpService`s with the goal to upgrade connections from `http` to `https` by redirection.

I was thinking it might be very useful to implement this on a high-level e.g. `actix-web`. Would that be acceptable or is this out of scope? I am willing to implement this myself.

**Comment by fafhrd91** [comment]
closing. just open PR if you'll get any code
