### ISSUE TITLE
Do you plan to migrate from tokio to async-std when it matures ?

### ISSUE THREAD

**Issue by librelois** [actix/actix-net#79]
It seems relevant, particularly for performance reasons, to consider migration to `async-std`: https://async.rs/blog/stop-worrying-about-blocking-the-new-async-std-runtime/

Indeed, `async-std` handles blocking calls not anticipated by the developer better than `tokio`: 

> The new runtime detects blocking automatically. We don’t need spawn_blocking anymore and can simply deprecate it.

`async-std` also offers the advantage of not paying the cost of spawning a new thread if the blocking call is only blocking for a very short time:

> The new runtime makes blocking efficient. Rather than always paying the cost of spawn_blocking, we only offload blocking work to a separate thread if the work really blocks.

So, it seems relevant to aim for a migration to `async-std` in the medium term, even if I understand that there are other priorities at the moment :)

**Comment by fafhrd91** [comment]
actix/actix-web is single threaded system. I do not expect async-std would give any performance benefits, I'd expect 25% drop in performance actually.

**Comment by librelois** [comment]
> actix/actix-net/actix-web is single threaded system

`actix-web` is based on `actix-rt`, itself based on `tokio`.
The execution of all futures is handled by the runtime of `tokio`, which is less efficient than the runtime of `async-std`.

If an `actix-web` user needs blocking calls to answer a request, he will have to use the tokio's spawn_blocking function, otherwise he will lose all interest in the asynchronous (see blocking problem: https://stjepang.github.io/2019/12/04/blocking-inside-async-code.html).

Of course, an actix user can always combine the 2 runtimes `tokio `+ `async-std` but using 2 runtimes at the same time is not efficient at all.

Perhaps it would be a good idea to perform some benchmark tests to verify each hypothesis :)

**Comment by fafhrd91** [comment]
you need to provide benchmarks. I doubt async-std is close to tokio in real io workload, and I don't care about other type of workload

**Comment by librelois** [comment]
Okay, when `async-std` is mature I might go for it, but I can't guarantee anything. I'm already hard-pressed to find time for my open-source projects.

I'm curious what makes you think `tokio` would be faster than async-std in the real IO world?

In the real IO world, the problem of blocking calls in asynchronous code is even more prevalent, and this problem is not handled automatically by `tokio` (it has to be handled explicitly by the developer).
`async-std` handles the problem of blocking calls in asynchronous code much better, in that the developer's code using `actix` will necessarily be faster.

Furthermore, since the Request Processing Factory is executed by `actix`, the asynchronous code of the actix user is necessarily orchestrated by `tokio`, it cannot be orchestrated by another futures executor.

The biggest performance losses may be on the user code side. A good compromise might be to let the user choose his runtime, perhaps via an optional feature.

**Comment by fafhrd91** [comment]
Blocking code in async context is a bug, if you encourage user to keep bugs, then your software just become buggy.

I don’t see anything actionable in this issue. You are free to fork and show results with `async-std`
