### ISSUE TITLE
actix_rt::spawn `Output = ()` constraint

### ISSUE THREAD

**Issue by milesgranger** [actix/actix-net#82]
Migrating to Actix-web 2.0 (thanks btw! :clap:) 

I used `tokio::spawn(...)` which had a return value. Since this doesn't work with `#[actix_rt::main]` I'm trying to rather make use of [`actix_rt::spawn`](https://docs.rs/actix-rt/1.0.0/actix_rt/fn.spawn.html) but I see it has a constraint of `Output = ()` 

Is it possible to remove this constraint, or (probably) am I going about this the wrong way?

**Comment by fafhrd91** [comment]
what is the point? you can just `await` on future

**Comment by milesgranger** [comment]
I was spawning a separate `std::thread` and wanted to join that in an `await`able way and from reading the docs on `tokio::task::spawn` it seemed it should handle this by potentially pushing the `join()` into a another thread. But upon reflection this was probably a bad approach anyway. Sorry to bother but thanks for the help. :+1:
