### ISSUE TITLE
Why was issue #83 deleted?

### ISSUE THREAD

**Issue by cdbattags** [actix/actix-net#87]
Issue #83 contained some pretty good discussion surrounding `unsafe` rust and I don't think we should ignore or delete a constructive conversation.

@fafhrd91, please please please can we try not to use phrases like "this patch is boring"?

❤️

**Comment by fafhrd91** [comment]
Next stage will be deleting organization. Please, do not continue

**Comment by cdbattags** [comment]
Why the hostility though? I know it's hard over text/internet/GitHub but I'm coming from a place of wanting this project to succeed.

**Comment by fafhrd91** [comment]
boring, because nobody actually wants to fix existing code, everyone just want to remove unsafe.

it is fixed, Actix-service 1.0.5 is released.

**Comment by cdbattags** [comment]
Thank you, Nikolay! I think it was just a misunderstanding of tone.

I appreciate everything you've done for this project this far and I think this is the future of server-side web development for sure.

Any sort of list of TODOs for the actix ecosystem right now?

**Comment by fafhrd91** [comment]
It is not very interesting to continue development. I will work only on functionality that is required for my job.

**Comment by cdbattags** [comment]
Maybe time to pass it off then? I think most of us want to do right by you and the project and get things under the org umbrella but Rust for sure needs a defacto web server (i.e. Express for the Node ecosystem) and that'll require much more continuous dev down the road, no?

Also, might I ask what's Microsoft's current stake in this project?
